version: '3.7'
services:
  app:
    build:
      context: .
      target: development
    environment:
      - NO_COLOR=true
      - PORT=80
    ports:
      - '3200:80'
    command: npm run start:dev
    volumes:
      - '.:/app'
      - fiubademy-public-api-node-modules:/app/node_modules
    networks:
      - fiubademy

networks:
  fiubademy:
    name: fiubademy

volumes:
  fiubademy-public-api-node-modules:
